In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Define the Neural Network

We want to be able to set the weight of the network manually

In [12]:
class NeuralNet(nn.Module):
    def __init__(self, in_dim=2, out_dim=2):
        super(NeuralNet, self).__init__()

        self.layer1=nn.Linear(in_features=in_dim, out_features=10)
        self.layer2=nn.Linear(in_features=10, out_features=out_dim)

        self.weights_initialization()
    
    def weights_initialization(self):
        for module in self.modules():
            if isinstance(module, nn.Linear):
                nn.init.xavier_uniform_(module.weight)  # This is the default in PyTorch
                nn.init.constant_(module.bias, 0)

    def forward(self, x):
        out = self.layer1(x)
        out = F.relu(out)
        out = self.layer2(out)
        out = F.relu(out)
        return out
    
    def get_params(self):
        params = []
        for p in self.parameters():
            params.append(p.data.view(-1))
            print(p)
        return params

In [ ]:
model = NeuralNet()
model.get_params()


Parameter containing:
tensor([[-0.4473,  0.5881],
        [ 0.1878, -0.0915],
        [-0.1317, -0.6962],
        [-0.3467, -0.7016],
        [-0.1025, -0.4769],
        [-0.5561,  0.1327],
        [-0.2340,  0.2707],
        [ 0.4072, -0.3388],
        [ 0.1807,  0.4253],
        [ 0.3893, -0.1310]], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
Parameter containing:
tensor([[ 0.2836,  0.4667,  0.3135, -0.5810,  0.3790, -0.3204,  0.3446,  0.0035,
          0.2094, -0.1178],
        [ 0.3839,  0.2882, -0.1170, -0.5665,  0.4906, -0.6535,  0.1110, -0.2311,
          0.4510, -0.0431]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


[tensor([-0.4473,  0.5881,  0.1878, -0.0915, -0.1317, -0.6962, -0.3467, -0.7016,
         -0.1025, -0.4769, -0.5561,  0.1327, -0.2340,  0.2707,  0.4072, -0.3388,
          0.1807,  0.4253,  0.3893, -0.1310]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([ 0.2836,  0.4667,  0.3135, -0.5810,  0.3790, -0.3204,  0.3446,  0.0035,
          0.2094, -0.1178,  0.3839,  0.2882, -0.1170, -0.5665,  0.4906, -0.6535,
          0.1110, -0.2311,  0.4510, -0.0431]),
 tensor([0., 0.])]